### ISSUE TITLE
Conditional and FromStyleBlockAttr

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#1]
```python
claddingMaterial = PerBuilding(Value(Alternatives(
    FromAttr("roof:material", FromAttr.String, CladdingMaterials),
    Conditional(
        lambda roof: roof.footprint.getStyleBlockAttr("roofShape") == "flat",
        RandomWeighted(( ("concrete", 1), ("gravel", 1) ))
    ),
    Conditional(
        lambda roof: roof.footprint.getStyleBlockAttr("roofShape") == "dome",
        Constant("glass")
    ),
    FromStyleBlockAttr("claddingMaterial", FromStyleBlockAttr.Footprint)
)))
```

**Comment by vvoovv** [comment]
`Condtional` has to arguments:
* a condition
* a value

It returns the value if the conditions is True, otherwise it returns None.

**Comment by vvoovv** [comment]
It can be represented in PML as:
```
claddingMaterial:
    FromAttr("roof:material") |
    RandomWeighted( ("concrete", 1), ("gravel", 1) ) if item.footprint["roofShape"] == "flat" |
    glass if item.footprint["roofShape"] == "dome" |
    item.footprint["claddingMaterial"]
;           
```

**Comment by vvoovv** [comment]
How to represent it in blosm nodes?

**Comment by vvoovv** [comment]
## Conditional node
Input sockets:
* condition
* value

Output sockets:
* value

**Comment by vvoovv** [comment]
## From Style Block node
Input sockets:
no

Output sockets:
* value

Properties:
* item (a choice between "self", "footprint" and "parent")
* attribute (a list of popular style block attributes)

**Comment by vvoovv** [comment]
## From OSM node
Input sockets:
no

Output sockets:
* value

Properties:
* OSM tag (a long list of the popular OSM tags)

**Comment by vvoovv** [comment]
## Alternatives node
Input sockets (probably 7 values is enough):
* value 1
* value 2
* value 3
* value 4
* value 5
* value 6
* value 7

Output sockets:
* value

**Comment by vvoovv** [comment]
> How to represent it in blosm nodes?

<hr></hr>

```python
    FromAttr("roof:material", FromAttr.String, CladdingMaterials),
```
**`From OSM`**.`value`  -> **`Alternatives`**.`value 1`
<hr></hr>

```python
    Conditional(
        lambda roof: roof.footprint.getStyleBlockAttr("roofShape") == "flat",
        RandomWeighted(( ("concrete", 1), ("gravel", 1) ))
    ),
```
**`RandomWeighted`**.`value`  -> **`Conditional`**.`value`
**`Conditional`**.`value`  -> **`Alternatives`**.`value 2`
<hr></hr>

```python
    Conditional(
        lambda roof: roof.footprint.getStyleBlockAttr("roofShape") == "dome",
        Constant("glass")
    ),
)))
```
**`CladdingMaterial`**.value -> **`Conditional`**.value
**`Conditional`**.`value`  -> **`Alternatives`**.`value 3`
<hr></hr>

```python
    FromStyleBlockAttr("claddingMaterial", FromStyleBlockAttr.Footprint)
```
**`From Style Block`**.`value`  -> **`Alternatives`**.`value 4`
<hr></hr>

And finally:
**`Alternatives`**.`value` -> **`Roof`**.`claddingMaterial`

**Comment by vvoovv** [comment]
## Per Building node
Input sockets:
* value

Output sockets:
* value

**Comment by vvoovv** [comment]
## Per Footprint node
Input sockets:
* value

Output sockets:
* value

**Comment by polarkernel** [comment]
I do not really understand the term _item_ in the condition. The proposition in PML is
```
glass if item.footprint["roofShape"] == "dome"
```
while the corrsponding Python code becomes
```
    Conditional(
        lambda roof: roof.footprint.getStyleBlockAttr("roofShape") == "dome",
        Constant("glass")
    ),
```
How can a translator find that the item is _roof_ here? Where does this context come from?

**Comment by vvoovv** [comment]
Any variable can be used in the Python's _lambda_ syntax:
`lambda anything: anything is None`

I'd suggest always use the variable _item_ in the Python code.

**Comment by vvoovv** [comment]
To be continued at https://github.com/prochitecture/pml/issues/6
