### ISSUE TITLE
pml.g4 and PML.g4

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#4]
How are [PML.g4](https://github.com/vvoovv/pml/blob/master/PML.g4) and [pml.g4](https://github.com/vvoovv/pml/blob/master/PML2PythonTranslator-Dev-I/pml_grammar/pml.g4) are related?

Is _pml.g4_ based on _PML.g4_?

**Comment by polarkernel** [comment]
Well, both describe in some way parts of the PML grammar. _PML,g4_ was a first approach proposed by Zkir in 2019. It is very simple and does not support the requirements for a translator. For instance attributes include alternatives, while alternatives require a complete different translation than simple attributes. _pml.g4_ is a new approach and is not related to _PML.g4_.  The old files _PML.g4_ and _example.pml_ should maybe get transferred from the root of the repository to to a separate folder, or even get removed.

**Comment by vvoovv** [comment]
Just deleted the top _PML.g4_. However I left top [example.pml](https://github.com/vvoovv/pml/blob/master/example.pml) since the translator is unable to process it.

**Comment by polarkernel** [comment]
There has never been a translator for this example.pml, because it was based to the grammar PML.g4, which is removed now.
