### ISSUE TITLE
notes about example.pml

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#6]
PML is intended to be easy to type manually.

So I suggest to use lowe case letters as much as possible to avoid switching from the lower case to capital case and back.

Item names should be lower-cased: _footprint_, _facade_ instead of _Footprint_, _Facade_
Also
_attr_ instead of _Attr_,
_random_normal_ instead of _RandomNormal_,
_random_weighted_ instead _RandomWeighted_

**Comment by vvoovv** [comment]
The outer square brackets [..] aren't need.

**Comment by vvoovv** [comment]
Quotation marks aren't need here:
```css
roofShape : flat;
```
instead of
```css
roofShape : "flat";
```

**Comment by vvoovv** [comment]
The original syntax for definitions was
```css
facade@brown_brick {
}
```
instead of
```css
Facade {
    defName : "brown_brick";
}
```

**Comment by polarkernel** [comment]
> So I suggest to use lowe case letters as much as possible to avoid switching from the lower case to capital case and back.

OK, I will change that. However I propose to keep the camel-cased attribute names, identical to the Python translation.

**Comment by polarkernel** [comment]
> Quotation marks aren't need here:

OK.

**Comment by polarkernel** [comment]
Note that I just provided a fragment of a translator to show the principle of a reusable _PythonCoder_. Many parts are not yet included, as for instance _defName_ (@)  _condition_, _Conditional_, _FromStyleBlockAttr_, _markup_, _styles_ and many others. From the last (_styles_) came the square brackets. It is quite difficult to write a consistent and translatable grammar and I wanted to start the discussion before all the work is done.

If you agree with my design in principle, I will continue to realize a complete translator.

**Comment by vvoovv** [comment]
> > So I suggest to use lowe case letters as much as possible to avoid switching from the lower case to capital case and back.
> 
> OK, I will change that. However I propose to keep the camel-cased attribute names, identical to the Python translation.

Ok.

**Comment by vvoovv** [comment]
> If you agree with my design in principle, I will continue to realize a complete translator.

Ok. See also #7

**Comment by polarkernel** [comment]
In default.py I found some attributes that I maybe do not yet understand completely, for instance
```
offset : (0.5, units.Level)
```
What does that mean? Can _units_ have any term like _Level_ or are there any limits?

Then
```
 width = useFrom("main_section")
```
Am I right when I assume that its argument refers always to an _id_, like _id = "main_section"_?

And
```
faces = smoothness.Smooth
```
Which parameters does _smoothness_ provide beside _Smooth_?

**Comment by vvoovv** [comment]
I haven't used the parameters `offset` and the function `useFrom(..)` so far.
It was planned to use `offset` for the windows in the staircase of the [appartments house](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/bldg2/zaandam_division.jpg).

I suggest to keep `offset` and `useFrom(..)` in mind, but introduce them in the parser rules of ANTLR grammar as soon as they are used in a real example.

**Comment by vvoovv** [comment]
The possible values of _smoothness_ are listed at https://github.com/vvoovv/blender-osm/blob/dev/grammar/smoothness.py

The attribute _faces_ can have two values: _smooth_ or _flat_. It's used be the dome, pyramidal and onion roofs. The other roofs ignore them.

**Comment by vvoovv** [comment]
You may have noticed an attribute _sharpEdges_ which was commented out.

It used if _faces_ is _smooth_. It specifies if a smooth face of the dome, pyramidal or onion roofs has sharp edges. If it's equal to _sides_, then only left and right edges of the smooth face are smooth.
