### ISSUE TITLE
PML to in-memory structures

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#7]
How does PML to in memory structures fit into the translator design?

**Comment by polarkernel** [comment]
I don't know. ANTLR4 requires its runtime to be installed in the Python interpreter using
```
pip install antlr4-python3-runtime
```
I don't think that we can expect users of Blender to install this runtime into the Python interpreter of Blender. Maybe the Python code could be loaded from a file, like _default.py_, but I didn't study that.

**Comment by vvoovv** [comment]
Python runtime for ANTLR is a collection of text files only (no binaries):
https://pypi.org/project/antlr4-python3-runtime/#files

It can be included with the addon.

**Comment by vvoovv** [comment]
Just pushed ANTLR4 runtime for Python3 into the repo:
https://github.com/vvoovv/pml/tree/master/antlr4

**Comment by vvoovv** [comment]
Actually it should in the _PML2PythonTranslator-Dev-I_ folder. So moved it there.

_antlr4-python3-runtime_ should be unistalled:
`pip uninstall antlr4-python3-runtime`

**Comment by polarkernel** [comment]
> How does PML to in memory structures fit into the translator design?

Ways more complicated than just Python code. I would propose a new class _PML2InMemoryTranslator_ that could use a _InMemoryListener_ and a _InMemoryCoder_ instead of the _PythonListener_ and _PythonCoder_. Naturally it could only run together with the imported osm classes. The parsing sequence would be quite different, as class or function names appear before their arguments. Neither studied nor tested yet.

**Comment by vvoovv** [comment]
A temporary (or even permanent!?) solution would be to output the Python code to a string instead of a Python file or stdout and then feed the string to _exec(..)_.

The following code worked for me :
```python
>>> from grammar import *
>>> exec("styleBlocks = [Facade()]")
>>> styleBlocks
[<grammar.Facade object at 0x0000029477181E48>]
```

**Comment by polarkernel** [comment]
That's a great idea! Maybe I change the _write()_ method in _PythonCoder_ to write to a string or maybe to _io.StringIO_. Then it can get written to a file or used by an _exec_, as you proposed.

**Comment by vvoovv** [comment]
Ok
