### ISSUE TITLE
.antlr folder

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#9]
What is the meaning of [.antlr](https://github.com/vvoovv/pml/tree/master/pml_grammar/.antlr) folder?

**Comment by polarkernel** [comment]
It can be deleted. This folder gets generated by the ANTLR4 parser generator when the grammar file is processed. It seems I have still to adapt my _.gitignore_. I had a lot of issues with that and it seems I stiil do not understand it correctly.

**Comment by vvoovv** [comment]
Ok. Just removed it.
